server:
  port: 80

#数据库
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/pokement?serverTimezone=Asia/Shanghai"
    username: root
    password: 123456


#系统配置
sysconfig:
  config:
    aaa: "aaa"
    appid: "assad"
    secret: "asssss"
    #加盐的长度
    random_salt_length: 10
    token_secret: "123"
    # 超时时间 小时
    expiretime: 24


